export const CH = {
  agents: {
    list: 'agents:list',
    get: 'agents:get',
    create: 'agents:create',
    update: 'agents:update',
    delete: 'agents:delete',
    reorder: 'agents:reorder',
    listTools: 'agents:listTools',
    setTool: 'agents:setTool',
    run: 'agents:run',
    cancel: 'agents:cancel',
    cancelAll: 'agents:cancelAll',
    clearRuns: 'agents:clearRuns',
    openExecutionsDir: 'agents:openExecutionsDir',
    activeRuns: 'agents:activeRuns',
    runEvent: 'agents:run:event',
    runs: 'agents:runs',
    artifacts: 'agents:artifacts',
    runTeam: 'agents:runTeam',
    teamEvent: 'agents:team:event',
    importTeam: 'agents:importTeam',
  },
  opportunities: {
    list: 'opportunities:list',
    get: 'opportunities:get',
    listFromFreelas: 'opportunities:listFromFreelas',
    rescore: 'opportunities:rescore',
    openJson: 'opportunities:openJson',
    openFreelasDir: 'opportunities:openFreelasDir',
  },
  sites: {
    list: 'sites:list',
    create: 'sites:create',
    update: 'sites:update',
    delete: 'sites:delete',
    scanNow: 'sites:scanNow',
  },
  scrapper: {
    start: 'scrapper:start',
    cancel: 'scrapper:cancel',
    event: 'scrapper:event',
  },
  tags: {
    list: 'tags:list',
    create: 'tags:create',
    update: 'tags:update',
    delete: 'tags:delete',
  },
  settings: {
    getAll: 'settings:getAll',
    get: 'settings:get',
    set: 'settings:set',
  },
  activity: {
    recent: 'activity:recent',
    event: 'activity:event',
  },
  summary: {
    daily: 'summary:daily',
  },
  system: {
    ready: 'system:ready',
    window: 'system:window', // close|minimize|maximize
  },
  app: {
    getConfig: 'app:getConfig',
    setConfig: 'app:setConfig',
    pickFile: 'app:pickFile',
    pickDirectory: 'app:pickDirectory',
    restart: 'app:restart',
    showItemInFolder: 'app:showItemInFolder',
    openPath: 'app:openPath',
    openWorkspaceDir: 'app:openWorkspaceDir',
  },
} as const;
